### ISSUE TITLE
patching error

### ISSUE THREAD

**Issue by Vorinc** [HexiDave/AssemblyPatcher#1] opened 2018-02-14 02:14 UTC
Starting to patch individual mods...
Successfully installed patch for ExampleMod.MoreQuickSlotsPatch
Successfully installed patch for ExampleMod.PullFromContainersPatch
Failed to patch the main assembly file:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
   at AssemblyPatcher.Program.PatchMainAssembly()
   at AssemblyPatcher.Program.Main(String[] args)

no idea what the cause is, but this has been happening with the version i built and the release off the git and i am not a competent coder

**Comment by HexiDave** [comment] 2018-02-14 04:03
Hey, no worries! If I had to guess, this is caused by the Assembly-CSharp.dll file being locked up by something else. Make sure Subnautica is closed and any decompiler programs (dnSpy and such) don't have the assembly file in memory. Then try running it again.

If it happens again, let me know if you have your Subnautica installed to the default folder and not an external Steam library folder (mine's on a different drive - haven't tested it with the default install yet). I know Windows has some issues with things in Program Files being manipulated, so I might need to add administrator permissions to the patcher.

Thanks for testing!

**Comment by HexiDave** [comment] 2018-02-14 04:08
Actually, scratch that - I'm seeing it too with the Release build. Investigating now.

**Comment by HexiDave** [comment] 2018-02-14 06:43
I see what the problem is - pretty obvious in hind-sight: The ExampleMod (and any mods, really) that reference Assembly-CSharp get the version that's currently being patched and this locks the file, preventing it from being overwritten.

I'll have a fix for it tomorrow; I need to adjust the folder paths a bit to "hide" the original file from the patcher and point it at the backup copy I keep instead.

**Comment by HexiDave** [comment] 2018-02-14 14:30
Commit eb39126 fixes this issue, closing. Please check the latest release for the updated patcher.

**Closed as completed by HexiDave** 2018-02-14 14:30 UTC
